# Generated by Django 5.1.3 on 2024-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=50)),
                ('slider_description', models.TextField()),
                ('slider_image', models.ImageField(upload_to='carousel/')),
            ],
        ),
    ]
