# Generated by Django 5.1.3 on 2024-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_aboutsection_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
