# Generated by Django 5.1.3 on 2024-12-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_button',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='Clothes', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='static/app1/images/clothes1.jpeg', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=50),
        ),
    ]
